name: 'test-set-env-var'
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        uses: ./actions/docker-local-set-env-name1
        with:
          python-version: 3.7

      - name: step2
        uses: winksaville/gha-js-set-env-var@main
        with:
          env-name: ${{ env.name1 }}
          env-value: ${{ runner.os }}-python-${{ env.name1 }}

      - name: done
        run: echo Done
