name: 'test-set-env-var'
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: ./actions/docker-local-set-env-var
      with:
        env-name: name1
        env-value: value1

    - uses: ./actions/docker-local-set-env-var
      with:
        env-name: name2
        env-value: ${{ env.name1 }}

    - name: check
      run: |
        if [ "$name2" = "value1" ]; then
          echo "name2 is value1"
        else
          echo "name2 is $name2, excepted value1"
          exit 1
        fi

    - name: done
      run: echo Done
