name: 'test-set-env-var'
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: step0
        uses: actions/checkout@v2

      - name: step1
        uses: ./actions/docker-local-set-env-name1

      ##This always works because loading a docker files
      ##causes the environment variables to be rebuilt.
      #- name: step2
      #  uses: ./actions/docker-local-set-env-var
      #  with:
      #    env-name: ${{ env.name1 }}
      #    env-value: ${{ runner.os }}-python-${{ env.name1 }}

      #This only works if fix-issue-416 is in act.
      - name: step2
        uses: ./actions/js-local-set-env-var
        with:
          env-name: ${{ env.name1 }}
          env-value: ${{ runner.os }}-python-${{ env.name1 }}

      - name: done
        run: echo Done
